<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AstcEncoderCSharp" Version="5.4.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TextureCompressor.Bitmap\TextureCompressor.Bitmap.csproj" />
    <ProjectReference Include="..\TextureCompressor\TextureCompressor.csproj" />
  </ItemGroup>

</Project>
