using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TextureCompressor.SourceGenerators;

[Generator]
public sealed class TextureFormatCatalogGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fields = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is FieldDeclarationSyntax,
                static (ctx, _) => GetTextureFormatFields(ctx))
            .SelectMany(static (fields, _) => fields)
            .Collect();

        context.RegisterSourceOutput(fields, static (ctx, fields) =>
        {
            var uniqueFields = fields
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static name => name, StringComparer.Ordinal)
                .ToImmutableArray();

            if (uniqueFields.Length > 0)
            {
                ctx.AddSource("TextureFormatCatalog.g.cs", SourceText.From(GenerateCatalog(uniqueFields), Encoding.UTF8));
            }
        });
    }

    private static ImmutableArray<string> GetTextureFormatFields(GeneratorSyntaxContext context)
    {
        var fieldDeclaration = (FieldDeclarationSyntax)context.Node;
        if (fieldDeclaration.Declaration.Type.ToString() != "TextureFormat")
        {
            return ImmutableArray<string>.Empty;
        }

        var containingType = context.SemanticModel.GetDeclaredSymbol(fieldDeclaration.Declaration.Variables[0])?.ContainingType;
        if (containingType?.ToDisplayString() != "TextureCompressor.Formats.TextureFormats")
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>();
        foreach (var variable in fieldDeclaration.Declaration.Variables)
        {
            if (context.SemanticModel.GetDeclaredSymbol(variable) is not IFieldSymbol field
                || field.DeclaredAccessibility != Accessibility.Public
                || !field.IsStatic
                || field.Type.ToDisplayString() != "TextureCompressor.Formats.TextureFormat")
            {
                continue;
            }

            builder.Add(field.Name);
        }

        return builder.ToImmutable();
    }

    private static string GenerateCatalog(ImmutableArray<string> fieldNames)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine();
        source.AppendLine("namespace TextureCompressor.Formats;");
        source.AppendLine();
        source.AppendLine("public static class TextureFormatCatalog");
        source.AppendLine("{");
        source.AppendLine("    private static readonly TextureFormat[] SAll =");
        source.AppendLine("    [");
        foreach (var fieldName in fieldNames)
        {
            source.Append("        TextureFormats.");
            source.Append(fieldName);
            source.AppendLine(",");
        }

        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    public static IReadOnlyList<TextureFormat> All => SAll;");
        source.AppendLine();
        source.AppendLine("    public static string GetFieldName(TextureFormat format)");
        source.AppendLine("    {");
        foreach (var fieldName in fieldNames)
        {
            source.Append("        if (format == TextureFormats.");
            source.Append(fieldName);
            source.AppendLine(")");
            source.AppendLine("        {");
            source.Append("            return nameof(TextureFormats.");
            source.Append(fieldName);
            source.AppendLine(");");
            source.AppendLine("        }");
            source.AppendLine();
        }

        source.AppendLine("        throw new ArgumentException($\"Unknown texture format '{format.Name}'.\", nameof(format));");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static TextureFormat Get(string name) =>");
        source.AppendLine("        TryGet(name, out var format)");
        source.AppendLine("            ? format");
        source.AppendLine("            : throw new ArgumentException($\"Unknown texture format '{name}'.\", nameof(name));");
        source.AppendLine();
        source.AppendLine("    public static bool TryGet(string name, out TextureFormat format)");
        source.AppendLine("    {");
        source.AppendLine("        ArgumentNullException.ThrowIfNull(name);");
        source.AppendLine();
        foreach (var fieldName in fieldNames)
        {
            source.Append("        if (string.Equals(name, nameof(TextureFormats.");
            source.Append(fieldName);
            source.Append("), StringComparison.OrdinalIgnoreCase)");
            source.AppendLine();
            source.Append("            || string.Equals(name, TextureFormats.");
            source.Append(fieldName);
            source.AppendLine(".Name, StringComparison.OrdinalIgnoreCase))");
            source.AppendLine("        {");
            source.Append("            format = TextureFormats.");
            source.Append(fieldName);
            source.AppendLine(";");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
            source.AppendLine();
        }

        source.AppendLine("        format = default;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine("}");

        return source.ToString();
    }
}
