<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TextureCompressor.Analysis\TextureCompressor.Analysis.csproj" />
    <ProjectReference Include="..\TextureCompressor.Bitmap\TextureCompressor.Bitmap.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Astc\TextureCompressor.FileFormats.Astc.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Dds\TextureCompressor.FileFormats.Dds.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Gif\TextureCompressor.FileFormats.Gif.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Jpeg\TextureCompressor.FileFormats.Jpeg.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Ktx\TextureCompressor.FileFormats.Ktx.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Png\TextureCompressor.FileFormats.Png.csproj" />
    <ProjectReference Include="..\TextureCompressor.FileFormats.Pvr\TextureCompressor.FileFormats.Pvr.csproj" />
    <ProjectReference Include="..\TextureCompressor\TextureCompressor.csproj" />
  </ItemGroup>

</Project>
